name: Deploy to GitHub pages
on:
  push:
    branches:
      - main

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v4

      - name: Install node 14.18 for the rest of the workflow
        uses: actions/setup-node@v3
        with:
          node-version: 14.18

      - name: Install node modules
        run: yarn install

      - name: Build CRA
        run: yarn run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          keep_files: true
